name: Procurasure CI/CD

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  build-and-test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: Build Frontend
        run: |
          cd frontend
          npm run build

  deploy-backend:

    needs: build-and-test

    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy Backend To AWS
        uses: appleboy/ssh-action@v1.2.0

        with:

          host: ${{ secrets.AWS_HOST }}

          username: ${{ secrets.AWS_USERNAME }}

          key: ${{ secrets.AWS_SSH_KEY }}

          script: |
            cd ~/Procurasure/backend

            git fetch origin

            git reset --hard origin/main

            npm install

            pm2 restart procurasure-api --update-env

            pm2 save

            pm2 list